services:
  - type: web
    name: nspxn-auto-review
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_API_KEY_HERE
